ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\User\AppData\Roaming
CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\crashpad_18828_PNMCZMKPCASPQVJX
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-D1KEAHC
COMSPEC=C:\WINDOWS\system32\cmd.exe
DRIVERDATA=C:\Windows\System32\Drivers\DriverData
EFC_2296=1
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\User
IGCCSVC_DB=AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAHPdCfSO99Eeyydsfu8QXcQQAAAACAAAAAAAQZgAAAAEAACAAAAARfejmBR92CoWlhMTdxRNvSh7bqK+0ivTXs0dpskULVgAAAAAOgAAAAAIAACAAAACSNmlDiWEyXeve0lBAI7XA9ceNRIkhwtNhOFdWATznHWAAAACbBx96C5xg0jxVHnWFvP0x4pavlLoKZ+CXIKoqtp0PvOovL9OaMBw4z7nMsUqp+MixVFF9uUVnDLVULI+vD41IE9tWtL7hpQe88OPjuEiMU+ggD6iVmVevqFHNhahW7WpAAAAAyqM3iDH4Z0LuFPlF/H51PX/ns6Lb9IfGVMuyzPqjlOeKCc3j3m81YTea5DgetU1Juc3mwXVpWYP3izJ7/YbtPg==
LOCALAPPDATA=C:\Users\User\AppData\Local
LOGONSERVER=\\DESKTOP-D1KEAHC
NUMBER_OF_PROCESSORS=8
ONEDRIVE=C:\Users\User\OneDrive
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
OS=Windows_NT
PATH=c:\Users\User\.vscode\extensions\ms-python.python-2025.0.0-win32-x64\python_files\deactivate\powershell;D:\python\venv\Scripts;C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\nodejs\;E:\Program\Git\cmd;C:\Program Files\MySQL\MySQL Server 8.0\bin;D:\slt\Release-24.08.0-0\poppler-24.08.0\Library\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Azure Data Studio\bin;C:\Users\User\AppData\Roaming\npm;C:\Users\User\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\User\AppData\Local\GitHubDesktop\bin;C:\Users\User\AppData\Local\Programs\mongosh\;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
POPPLER=D:\slt\Release-24.08.0-0\poppler-24.08.0\Library\bin
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8c01
PROGRAMDATA=C:\ProgramData
PROGRAMFILES=C:\Program Files
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMW6432=C:\Program Files
PSMODULEPATH=C:\Users\User\OneDrive\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\160\Tools\PowerShell\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\WINDOWS
TEMP=C:\Users\User\AppData\Local\Temp
TMP=C:\Users\User\AppData\Local\Temp
USERDOMAIN=DESKTOP-D1KEAHC
USERDOMAIN_ROAMINGPROFILE=DESKTOP-D1KEAHC
USERNAME=User
USERPROFILE=C:\Users\User
WINDIR=C:\WINDOWS
ZES_ENABLE_SYSMAN=1
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.97.2
LANG=en_US.UTF-8
COLORTERM=truecolor
PYDEVD_DISABLE_FILE_VALIDATION=1
DEBUGPY_ADAPTER_ENDPOINTS=c:\Users\User\.vscode\extensions\ms-python.debugpy-2025.0.1-win32-x64\.noConfigDebugAdapterEndpoints\endpoint-ada3b04611704dae.txt
VSCODE_ENV_PREPEND=PATH=c\x3a\Users\User\.vscode\extensions\ms-python.python-2025.0.0-win32-x64\python_files\deactivate\powershell;D\x3a\python\venv\Scripts;
BUNDLED_DEBUGPY_PATH=c:\Users\User\.vscode\extensions\ms-python.debugpy-2025.0.1-win32-x64\bundled\libs\debugpy
GIT_ASKPASS=c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
VSCODE_GIT_ASKPASS_NODE=C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-14115842ef-sock
VIRTUAL_ENV=D:\python\venv
VSCODE_ENV_REPLACE=VIRTUAL_ENV=D\x3a\python\venv:VIRTUAL_ENV_PROMPT=venv
VIRTUAL_ENV_PROMPT=venv
VSCODE_INJECTION=1
VSCODE_NONCE=9c683ae3-b4d9-4611-8bc3-2c9ab07af66f
VSCODE_STABLE=1
PYTHONUSERBASE=C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages
